name: .NET Build Publish NuGet GitHub Package

on:
  push:
    branches:
      - 'main'      

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: ${{ github.event.inputs.projectPath }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore ${{ github.event.inputs.projectPath }}
        shell: bash

      - name: Build
        run: dotnet build ${{ github.event.inputs.projectPath }} --configuration Release --no-restore
        shell: bash

      - name: Test
        run: dotnet test ${{ github.event.inputs.projectPath }} --configuration Release --no-build --verbosity normal
        shell: bash

      - name: Add GitHub NuGet source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username ${{ github.actor }} --password ${{ secrets.PERSONAL_ACCESS_TOKEN }} --store-password-in-clear-text
        shell: bash

      - name: Clean output directory
        run: rm -rf nuget-packages
        shell: bash

      - name: Pack
        run: dotnet pack ${{ github.event.inputs.projectPath }} --output nuget-packages --configuration Release --no-build
        shell: bash

      - name: Push to GitHub Packages
        run: dotnet nuget push nuget-packages/*.nupkg --skip-duplicate -s "github" --api-key ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        shell: bash

      - uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/NuGet_${{steps.get-version.outputs.version}}',
              sha: context.sha
            })
