name: Build and Publish NuGet Package to GitHub

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'main'
      - 'master'

env:
  PROJECT_PATH: './src/Microsoft.FeatureManagement.Plus/Microsoft.FeatureManagement.Plus.csproj'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: ${{ env.PROJECT_PATH }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}"
        shell: bash

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore
        shell: bash

      # Optional: Only run tests if you have test projects
      # - name: Test
      #   run: dotnet test ./tests/YourTestProject.csproj --configuration Release --no-build --verbosity normal
      #   shell: bash

      - name: Add GitHub NuGet source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --store-password-in-clear-text --name "github" --username "${{ github.actor }}" --password "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        shell: bash

      - name: Clean output directory
        run: rm -rf nuget-packages
        shell: bash

      - name: Pack
        run: dotnet pack "${{ env.PROJECT_PATH }}" --output nuget-packages --configuration Release --no-build
        shell: bash

      - name: Push to GitHub Packages
        run: dotnet nuget push nuget-packages/*.nupkg --skip-duplicate --no-symbols -s "github" --api-key "${{ secrets.PERSONAL_ACCESS_TOKEN }}" --store-password-in-clear-text
        shell: bash

      - uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/NuGet_${{ steps.get-version.outputs.version }}',
              sha: context.sha
            })