name: Build and Publish NuGet Package to GitHub

on:
  push:
    branches:
      - 'main'
      - 'master'

env:
    PROJECT_PATH: '/src/Microsoft.FeatureManagement.Plus/Microsoft.FeatureManagement.Plus.csproj'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      # This step requires projectPath to be provided. If it's not set up as an input, consider hardcoding or using a default.
      - uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        with:
          proj-path: '/src/Microsoft.FeatureManagement.Plus/Microsoft.FeatureManagement.Plus.csproj'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH
        shell: bash

      - name: Build
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore
        shell: bash

      - name: Test
        run: dotnet test $PROJECT_PATH --configuration Release --no-build --verbosity normal
        shell: bash

      - name: Add GitHub NuGet source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.actor }}" --password "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        shell: bash

      - name: Clean output directory
        run: rm -rf nuget-packages
        shell: bash

      - name: Pack
        run: dotnet pack $PROJECT_PATH --output nuget-packages --configuration Release --no-build
        shell: bash

      - name: Push to GitHub Packages
        run: dotnet nuget push nuget-packages/*.nupkg --skip-duplicate -s "github" --api-key "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        shell: bash

      - uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/NuGet_${{ steps.get-version.outputs.version }}',
              sha: context.sha
            })